name: hs-chess
version: 0.1.0.0
github: "githubuser/hs-chess"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/githubuser/hs-chess#readme>

dependencies:
  - base >= 4.7 && < 5
  - haskeline >= 0.8.1.2
  - rainbow >= 0.34.2.2
  - text >= 1.2.0.0

executables:
  hs-chess-exe:
    main: chess.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -prof
      - -fprof-auto
      - -fprof-cafs
